### ISSUE TITLE
Support for a private issuerUrl and public issuerUrl

### ISSUE THREAD

**Issue by kjoconnor** [oxyno-zeta/s3-proxy#108]
Skipped the bug report template as this is more of a question as opposed to a bug report, let me know if you'd prefer I go through those steps!

I'm running `v3.0.3 (git commit: 81b70c4)` via the latest version of your helm chart.

I'm trying to use s3-proxy with an in cluster OIDC provider (dex). The flow I'm imagining is that end users are directed to some "public" facing hostname for dex, but for in cluster traffic (the token exchange) that would go to a different hostname. With one issuerUrl, I either have to send the private token exchange over the public internet, or I have to have some strange setup for end users to be able to port-forward or somehow otherwise access the private interface for dex.

Ideally I think it would be something like:
```yaml
authProviders:
  oidc:
    provider1:
      publicIssuerUrl: dex.mydomain.com
      privateIssuerUrl: dex.dex.svc.cluster.local
```

I'm pretty new to getting this type of thing set up so if I'm missing something simple please let me know. Thank you for the project!

**Comment by oxyno-zeta** [comment]
I will reformulate this a bit just to be sure I've correctly understood your question.

You have a S3-proxy that will be called by people from outside with a public url (here: http://pub-s3-proxy.com) with a public IDP (here: http://pub-idp.com). The same S3-proxy will be also called from inside a cluster with the internal url (here: http://s3-proxy.s3-proxy.svc.cluster.local). And you would like that the IDP in this case will be http://idp.svc.cluster.local . Am I correct ?

If no, can you elaborate more your question please ?

If yes, I have another idea for you.

What about creating 2 differents oidc providers, one will be the public one and the second will be the private. After that you can create 2 different `target` for the same bucket BUT with the 2 domains as mount points with the 2 different oidc providers.

Example:

```yaml
authProviders:
  oidc:
    provider1:
      issuerUrl: dex.mydomain.com
    provider2:
      issuerUrl: dex.dex.svc.cluster.local

targets:
- name: private
  mount:
    path:
    - /
    host: s3-proxy.s3-proxy.svc.cluster.local
  resources:
  - path: /*
    provider: provider2
    ...

- name: public
  mount:
    path:
    - /
    host: pub-s3-proxy.com
  resources:
  - path: /*
    provider: provider1
    ...
```
What do you think of this ?
