### ISSUE TITLE
Question: how to better deal with requests to folder prefixes?

### ISSUE THREAD

**Issue by chiefy** [oxyno-zeta/s3-proxy#130]
**Is your feature request related to a problem? Please describe.**
Currently we're using docusaurus to deploy static sites to s3, some urls that Docusaurus generates do not contain trailing slashes (ex. `mysite.com/some_section`), though clicking through from a parent to the sub-section page will work due to JS/HTML magic, a hard-link will not redirect to `mysite.com/some_section/` which correctly serves up the `indexDocument` (in this case: `index.html`). 

**Describe the solution you'd like**
An option to force the proxy to check if a document is a folder, if so recurse into it and serve up `indexDocument` etc.

**Describe alternatives you've considered**
An alternate solution is to just use URL rewriting, but we're using AWS ALBs which won't work in that scenario and though other reverse-proxies will remedy the situation, I am hesitant to put another layer in between the ALB and S3Proxy.

**Comment by oxyno-zeta** [comment]
Hello,

That's another good issue :+1: .

I must confess that I already had this problem but I didn't find any solution just by changing the code... The problem I have is that, I can't know that a path can be a "folder". In S3, folders don't exists. It's a human view if I can say this :). In S3 list results, what we consider as folders are other levels of "prefixes". Hope it is more clear about the problem.

But, you give me another idea with your issue. 

What I can imagine now is to add an option with a list of glob path that will consider all path under those as a "folder" per se and will be served as served so indexDocument option will be used.
This will force a redirect on client side in order to manage it correctly after.

This will be represented as this for example:

```yaml
targets:
  - name: first-bucket
    mount:
      host: api.localhost:8080
      path:
        - /v2/
    bucket:
      name: oxyno-test
      region: eu-west-1
    indexDocument: index.html
    forceTrailingSlashPathList:
    - /folder1/**
    - /**
```

An example of flow will be:

-> http://api.localhost:8080/v2/folder1 -> TEMPORARY REDIRECT 302 http://api.localhost:8080/v2/folder1/ -> match as "folder"

What do you think of this ? Is this idea can solve your problem ?

By the way, this seems to be a good idea to do for me :smile: . I will probably do it for other usages.

Thanks !
