### ISSUE TITLE
GitLab Token Refresh Failing

### ISSUE THREAD

**Issue by atzawada** [oxyno-zeta/s3-proxy#217]
When using GitLab OIDC it seems like the authorization token doesn't get refreshed after the initial login. I can log in successfully and browse the files, but after awhile I get an internal server error stating `oidc: token is expired` with not much to go on in the proxy logs. I assume some call to GitLab is failing in the background. Any thoughts on how to debug this?

Here is my config yaml:

```yaml
# Log configuration
    log:
      # Log level
      level: info
      # Log format
      format: text

    # Authentication Providers
    authProviders:
      oidc:
        gitlab:
          clientID: <redacted>
          clientSecret:
            <redacted>
          state: <redacted>
          issuerUrl: https://<redacted>.net:5443
          redirectUrl: https://<redacted>.io # /auth/oidc/callback will be added automatically
          scopes: # OIDC Scopes (defaults: openid, email, profile)
            - openid
            - email
            - profile
          # groupClaim: groups # path in token
          # cookieSecure: true # Is the cookie generated secure ?
          # cookieName: oidc # Cookie generated name
          emailVerified: false # check email verified field from token
          # loginPath: /auth/provider1 # Override login path dynamically generated from provider key
          callbackPath: /oauth2/callback

    # List targets feature
    # This will generate a webpage with list of targets with links using targetList template
    listTargets:
      # To enable the list targets feature
      enabled: false
      ## Mount point
      mount:
        path:
          - /
        # A specific host can be added for filtering. Otherwise, all hosts will be accepted
        # host: localhost:8080
      ## Resource configuration
      resource:
        # A Path must be declared for a resource filtering
        path: /
        # HTTP Methods authorized (Must be in GET, PUT or DELETE)
        methods:
          - GET
        # Whitelist
        whitelist: true
        # A authentication provider declared in section before, here is the key name
        provider: gitlab
        # OIDC section for access filter
        oidc:
          # NOTE: This list can be empty ([]) for authentication only and no group filter
          authorizationAccesses: [] # Authorization accesses : groups or email or regexp

    # Targets map
    targets:
      api-docs:
        ## Mount point
        mount:
          path:
            - /
        # ## Resources declaration
        # ## WARNING: Think about all path that you want to protect. At the end of the list, you should add a resource filter for /* otherwise, it will be public.
        resources:
          # A Path must be declared for a resource filtering (a wildcard can be added to match every sub path)
          - path: "/*"
            provider: gitlab
            # OIDC section for access filter
            oidc:
              # NOTE: This list can be empty ([]) for authentication only and no group filter
              authorizationAccesses: [] # Authorization accesses : groups or email or regexp
        # Actions
        actions:
          # Action for GET requests on target
          GET:
            # Will allow GET requests
            enabled: true
          PUT:
            # Will allow PUT requests
            enabled: false
            # Configuration for PUT requests
          DELETE:
            # Will allow DELETE requests
            enabled: false
        # Bucket configuration
        bucket:
          name: <redacted>
          prefix:
          region: <redacted>
          s3Endpoint:
          disableSSL: false
          # s3ListMaxKeys: 1000
          credentials:
            accessKey:
              <redacted>
            secretKey:
              <redacted>
```

**Expected behavior**
The token should be refreshed and the content should be able to be accessed.

**Version and platform (please complete the following information):**
- Docker image tag 4.1.0 via Helm deployment
