### ISSUE TITLE
Issues with login redirect

### ISSUE THREAD

**Issue by mogggggg** [oxyno-zeta/s3-proxy#220]
- Platform: Linux
 - Arch: amd64
 - Version: 4.1.0

Hey there,
First off this is a great tool, thanks for building it! I'm using it with Google OAuth as a proxy for S3 artifacts for [Buildkite builds](https://buildkite.com/docs/agent/v3/cli-artifact#using-your-private-aws-s3-bucket). I'm having an issue where the OAuth redirect gets stuck after a successful login. It works properly when I hit the s3-proxy URL directly, but if I try and use the links created by Buildkite it gets stuck. If I close the tab and refresh the page I can download the artifacts though, so the authentication has actually worked.

I've put the logs into debug mode and I think it's because it's trying to use HTTP whereas we redirect all traffic to HTTPS on our load balancers? It sounds kind of similar to [this](https://github.com/oxyno-zeta/s3-proxy/pull/156) issue.

This is the requested URL which throws a 307:
```
https://<my_domain>/auth/google/callback?state=<state>:http://<my_domain>/b1258790-5738-4f46-aa8c-44b04c99df8f/<artifact_name>&code=<code>&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20openid%20https://www.googleapis.com/auth/userinfo.email&authuser=0&hd=<my_domain>&prompt=none
```

This is a log from one of the pods:
```
level=info msg="request complete" client_ip=10.0.20.71 http_method=GET http_proto=HTTP/1.1 http_scheme=http remote_addr=10.0.20.71 req_id=s3-proxy-6bdb5545fb-k5d9n/BYqOqpjgJ4-002249 resp_bytes_length=13756449 resp_elapsed_ms=1332.687785 resp_status=200 uri="http://<my_domain>/b1258790-5738-4f46-aa8c-44b04c99df8f/<artifact_name>" user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
```

As you can see part of the redirect uses `http://` and the `http_scheme` in the pod's logs is `http` too. I'm not 100% sure if this is the actual issue or if it's something I need to raise with buildkite.

My config:
```yaml
    log:
      level: error
      format: text

    authProviders:
      oidc:
        google:
          clientID: **************
          clientSecret:
            value: **************
          state: **************
          issuerUrl: https://accounts.google.com
          redirectUrl: https://**************
          emailVerified: true

    targets:
      buildkite-artifacts:
        mount:
          path:
            - /
        resources:
        - path: /*
          methods:
            - GET
          provider: google
          oidc:
            authorizationAccesses:
              - email: "^([^@]+)@<my_domain>\\.<tld>$"
                regexp: true

        bucket:
          name: **************
          region: ap-southeast-2
```
