### ISSUE TITLE
I can't disable index page

### ISSUE THREAD

**Issue by martonsz** [oxyno-zeta/s3-proxy#237]
**Describe the bug**
I am trying to disable the index page by configuring [ListTargetsConfiguration](https://s3-proxy.github.oxyno-zeta.com/configuration/structure/#listtargetsconfiguration)

**To Reproduce**
I have tried the following configurations. But they all show the index page.

```yaml
log:
  level: debug
  format: text
listTargets:
  enabled: false
  mount:
    path:
      - /
targets:
  first-bucket:
    mount:
      path:
        - /
    bucket:
      name: foo-common.example.com
      prefix:
      region: gra
      s3Endpoint: https://s3.gra.cloud.ovh.net
      disableSSL: false
      s3ListMaxKeys: 1000
      credentials:
        accessKey:
          value: testing
        secretKey:
          value: testing
```

```yaml
log:
  level: debug
  format: text
listTargets:
  enabled: false
  mount:
    path:
      - /foo-common.example.com/
targets:
  first-bucket:
    mount:
      path:
        - /foo-common.example.com/
    bucket:
      name: foo-common.example.com
      prefix:
      region: gra
      s3Endpoint: https://s3.gra.cloud.ovh.net
      disableSSL: false
      s3ListMaxKeys: 1000
      credentials:
        accessKey:
          value: testing
        secretKey:
          value: testing
```

```yaml
log:
  level: debug
  format: text
listTargets:
  enabled: false
  mount:
    path:
      - /
targets:
  first-bucket:
    mount:
      path:
        - /foo-common.example.com/
    bucket:
      name: foo-common.example.com
      prefix:
      region: gra
      s3Endpoint: https://s3.gra.cloud.ovh.net
      disableSSL: false
      s3ListMaxKeys: 1000
      credentials:
        accessKey:
          value: testing
        secretKey:
          value: testing
```

**Expected behavior**
Do not show and index page with files when I visit `https://mys3proxy.example.com`

**Version and platform (please complete the following information):**
 - Helm chart: [2.7.0](https://artifacthub.io/packages/helm/oxyno-zeta/s3-proxy/2.7.0)
 - Image: oxynozeta/s3-proxy:4.1.0
 - Kubernetes 1.21.1 (created with [kind](https://github.com/kubernetes-sigs/kind), running in Docker Desktop on Windows using WSL 2)

**Comment by oxyno-zeta** [comment]
Hello, 

Thanks for your bug. I supposed that what you are calling "index page" is the target list right ?
I'm sorry but I can't reproduce that issue. 
When I put the `enabled: false` in the `listTargets`, everything is working well.

Maybe you should try with the version `4.1.3`. Another possibility: Clean the configuration to remove completely the `listTargets` part.

Regards,

**Comment by martonsz** [comment]
I missed that there was a new version. I just used the default image for the latest helm chart [2.7.0](https://artifacthub.io/packages/helm/oxyno-zeta/s3-proxy/2.7.0)

I'm having the same issue with the latest version `oxynozeta/s3-proxy:4.1.3`

Here is my full config copied from the running pod using the command `kubectl exec deploy/s3-proxy -- cat conf/config.yaml | sed '/^[[:space:]]*#/d'| sed '/^$/d'`

```yaml
log:
  level: debug
  format: text
targets:
  first-bucket:
    mount:
      path:
        - /
    bucket:
      name: foo-common.example.com
      prefix:
      region: gra
      s3Endpoint: https://s3.gra.cloud.ovh.net
      credentials:
        accessKey:
          path: /proxy/secret-files/s3-access-key-id.txt
        secretKey:
          path: /proxy/secret-files/s3-secret-access-key.txt
```
