### ISSUE TITLE
s3 client example

### ISSUE THREAD

**Issue by harlequin** [oxyno-zeta/s3-proxy#255]
**Describe the bug**
I have tried to get the minio client working with s3-proxy, but I always receive an error

```
$ ./mc ls proxy/airflow/logs/

mc.exe: <ERROR> Unable to list folder. Get "http://127.0.0.1:8080/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=logs%2F": net/http: invalid header field value "AWS4-HMAC-SHA256 Credential=xxx/20220309/\n  \n/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=32330c79527f6f7c1498f56ad01324a5f535d6935784d438eeb01eb8368f0bac" for key Authorization
```
**Configuration**
```
authProviders:
  basic:
    provider1:
      realm: MyBasic

targets:  
  target1:
    mount:
      path:
        - /airflow/
    bucket:
      name: airflow # Bucket Name on remote storage system
      prefix:
      region: eu-west-1
      s3Endpoint: https://somewhere:10447
      disableSSL: false

      credentials:
        accessKey:
          value: xxx   
        secretKey:
          value: xxx 
    resource:
      - path: /airflow/*
        provider: provider1
        basic:
          credentials:
            - user: xxx
              password:
                value: xxx
```

mc client config

```
"proxy": {
   "url": "http://127.0.0.1:8080",
    "accessKey": "xxx",
    "secretKey": "xxx",
    "api": "S3v4",
    "path": "auto"
},
```
