### ISSUE TITLE
Document and sanitize input for secret files

### ISSUE THREAD

**Issue by skeenan947** [oxyno-zeta/s3-proxy#260]
**Describe the bug**
Secret file (for CredentialSecret) input is not sanitized, and there isn't any documentation stating what the format is for secret files.

**To Reproduce**
Use secret file (credentials.path) in bucket config, e.g.
```
      bucket:
          name: something
          credentials:
            accessKey:
              path: /proxy/secret-files/metrics-bucket-key
            secretKey:
              path: /proxy/secret-files/metrics-bucket-secret
```

**Expected behavior**
I would like to see documentation stating that these files need to have nothing but the secret in them.  I would also expect that the input is sanitized, at least having trailing `\n` removed.
Ideally, it would be preferred to put both key and secret in a single file, structured as YAML

**Version and platform (please complete the following information):**
 - Platform: linux
 - Arch: amd64
 - Version: v4.4.0

**Additional context**
Figuring out how this was supposed to be used, (helm -> k8s secrets as files, with literally nothing but the secret/key in them) took too long and ended up with me reading through code in order to figure out what usage is supposed to look like.
I'd actually prefer to use env vars from secret, but secrets are only exposed as helm values, rather than as native k8s secret config.
