### ISSUE TITLE
How to set authorizationAccesses

### ISSUE THREAD

**Issue by gsalvatella** [oxyno-zeta/s3-proxy#265]
I'd like to restrict access to a bucket to members belonging to certain groups in my OIDC provider. I'm not sure how to go about it with `authorizationAccesses`. How can I let members of e.g. only  `group1` and `group2` access the bucket elements?

```
targets:
  target1:
    resources:
      - path: /*
        provider: gitlab
        oidc:
          authorizationAccesses:
            - group: only_one_group?
     bucket:
       ...
```

**Comment by oxyno-zeta** [comment]
Hello,

After reading the documentation, something isn't clear in it. I will update it.
The authorizationAccesses list is done on the "OR" principle. Another to say it is : you are authorized as soon as 1 thing (email or gorup) is matching.

Example:
```yaml
targets:
  target1:
    resources:
      - path: /*
        provider: gitlab
        oidc:
          authorizationAccesses:
            - group: group1
            - group: group2
     bucket:
       ...
```
We consider those users:
- Jean Dupont with `group1` and `group2`
- Astérix with `group1` and `group3`
- Obélix with `group3`

Accesses will be:
- Jean Dupont: Ok because he is in `group1` (and `group2` but this one isn't matching the first)
- Astérix: Ok because he is in `group1`
- Obélix: Forbidden because he isn't in any of `group1` or `group2`

To conclude, if you want to have a AND accesses list (following the example before, only Jean Dupont is authorized), you will have to change the authorization mechanism to [OPA](https://oxyno-zeta.github.io/s3-proxy/configuration/structure/#opaserverauthorization).

Hope this is more clear now.

Oxyno-zeta

PS: I'm sorry for the names, this is too early to have wonderful ideas :)
