### ISSUE TITLE
PUT and DELETE operations not working

### ISSUE THREAD

**Issue by SheverNts** [oxyno-zeta/s3-proxy#306]
Getting 405(Method Not Allowed) when trying to PUT and DELETE file operations. Get operation is working as expected.

**To Reproduce**

Docker Run:
```
docker run -d --name s3-proxy -p 0.0.0.0:8080:8080 -p 0.0.0.0:9090:9090 -v $PWD/conf:/proxy/conf -v $PWD/password:/proxy/password oxynozeta/s3-proxy
```

conf.yaml
```
log:
  level: debug
  format: text

# Server configurations
server:
  listenAddr: ""
  port: 8080
  compress:
    enabled: false
    level: 5
    types:
      - text/html
      - text/css
      - text/plain
      - text/javascript
      - application/javascript
      - application/x-javascript
      - application/json
      - application/atom+xml
      - application/rss+xml
      - image/svg+xml

# Authentication Providers
authProviders:
  basic:
    provider2:
      realm: "My Basic Auth Realm"

# Targets map
targets:
  drops:
    ## Mount point
    mount:
      path:
        - /
    resources:
    #   # A Path must be declared for a resource filtering (a wildcard can be added to match every sub path)
      - path: /*
        methods:
          - PUT
          - GET
          - DELETE
        provider: provider2
        basic:
          credentials:
            - user: user1
              password:
                path: /proxy/password
    ## Bucket configuration

    bucket:
      name: example.com
      prefix:
      region: us-east-1
      s3Endpoint:
      disableSSL: false
      s3ListMaxKeys: 100

```

Error(Delete):
```
curl -vvv -X DELETE  -u user1:test http://example.com:8080/conf/conf.yaml
*   Trying 10.205.196.37...
* TCP_NODELAY set
* Connected to example.com (10.205.196.37) port 8080 (#0)
* Server auth using Basic with user 'user1'
> DELETE /conf/conf.yaml HTTP/1.1
> Host: example.com:8080
> Authorization: Basic dXNlcjE6dGVzdA==
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 405 Method Not Allowed
< Cache-Control: no-cache, no-store, no-transform, must-revalidate, private, max-age=0
< Expires: Thu, 01 Jan 1970 00:00:00 UTC
< Pragma: no-cache
< X-Accel-Expires: 0
< Date: Tue, 02 Aug 2022 09:41:10 GMT
< Content-Length: 0
<
* Connection #0 to host example.com left intact
* Closing connection 0
```
Error(PUT):
```
 curl -vvv  -X PUT -u user1:test  -F file=@/Users/natsaiso/conf/conf.yaml http://example.com:8080/conf/
*   Trying 10.205.196.37...
* TCP_NODELAY set
* Connected to example.com (10.205.196.37) port 8080 (#0)
* Server auth using Basic with user 'user1'
> PUT /conf/ HTTP/1.1
> Host: example.com:8080
> Authorization: Basic dXNlcjE6dGVzdA==
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 1567
> Content-Type: multipart/form-data; boundary=------------------------f2ad7fbb60de7cc7
> Expect: 100-continue
>
< HTTP/1.1 405 Method Not Allowed
< Cache-Control: no-cache, no-store, no-transform, must-revalidate, private, max-age=0
< Expires: Thu, 01 Jan 1970 00:00:00 UTC
< Pragma: no-cache
< X-Accel-Expires: 0
< Date: Tue, 02 Aug 2022 09:43:54 GMT
< Content-Length: 0
< Connection: close
<
* Closing connection 0
```

**Version and platform (please complete the following information):**
 - Platform Linux (docker)
 - Arch x86_64
 - Version v4.5.0 (git commit: 53d4768) built on 2022-03-30T19:42:02Z
