### ISSUE TITLE
folder-list page leads to Internal server error

### ISSUE THREAD

**Issue by j0nm1** [oxyno-zeta/s3-proxy#310]
Hi,
I'm trying to disable the folder list page (index). But as there is no direct way, I'm overriding the template as described here: https://github.com/oxyno-zeta/s3-proxy/issues/237. But this seems not to work as expected.

**Describe the bug**
When using an access token that only has the permissions `"s3:GetObject"` it seems to be impossible to disable the `folder-list` page without overriding the `internal-server-error` template as well. The proxy application will receive a 403 when trying to receive the list of folders (even if the template does not require it). This leads to the internal server error page even when replacing the `folder-list` template.

**To Reproduce**
1. Configure the proxy application with an access key with the policy:
```
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "s3:GetObject"
   ],
   "Resource": [
    "arn:aws:s3:::bucket-name",
    "arn:aws:s3:::bucket-name/*"
   ]
  }
 ]
}
```
2. Change the config to use the 403 template for the `list-folder` page (as I want to disable the access to the folders):
```
      templates:
        helpers:
          - templates/_helpers.tpl
        folderList:
          path: templates/forbidden-error.tpl
          headers:
            Content-Type: '{{ template "main.headers.contentType" . }}'
          status: "403"
```
3. When accessing the `folder-list` page you will receive an internal server error page instead of the expected `access-denied` page.

**Expected behavior**
The `folder-list` page returns the `access-denied` template (or there is a way to disable the listing entirely).
