### ISSUE TITLE
Receiving `500 Internal Server Error` instead of `403 Forbidden`

### ISSUE THREAD

**Issue by redat00** [oxyno-zeta/s3-proxy#437]
**Describe the bug**

Hi, me again, this time for an issue I'm having. I tried to set-up the proxy in the most simple way, using basic authentication. 
I tried to follow the documentation as much as I could, but I think that I might be missing something regarding of the different parts interact with each other (resources, targets etc..)

When running a cURL request with the correct username and password, everything's fine. 
But with a wrong username and password, I'm getting a `500 Internal Server Error` ...

As I said, I'm unsure about how everything interact with each other : 
- Is the authProvider mandatory ? 
- Should I still set the provider in the mount, even if I'm setting auth in the resources ? 

I can copy/paste the stack trace if needed, but it can easily be reproduced.

**To Reproduce**

Start the server with the following configuration. 

```yaml
# Log configuration
log:
  level: debug
  format: json
  filePath: /var/log/s3-proxy.log

# Server configuration
server:
  listenAddr: 0.0.0.0
  port: 8080

# Targets configuration
targets:
  test-bucket:
    resources:
      - path: /
        methods: GET
        basic:
          credentials:
            user: user1
            password:
              value: secret
      - path: /
        methods: PUT
        basic:
          credentials:
            user: user2
            password:
              value: secret
    mount:
      path:
        - /
      provider: authprovider
      methods:
        - GET
        - PUT
        - DELETE
    bucket:
      name: test
      region: default
      s3Endpoint: storage.example.org
      credentials:
        accessKey:
          value: random
        secretKey:
          value:  random
    actions:
      GET:
        enabled: true
      PUT:
        enabled: true

authProviders:
  basic:
    authprovider:
      realm: Auth Provider
```

Then run the following command : 

This one will succeed
```bash
curl -XGET http://127.0.0.1:8080/ --user "user1:secret"
```

This one will not, but not in the expected way
```bash
curl -XGET http://127.0.0.1:8080/ --user "user1:badpassword"
```

**Expected behavior**

I expect to be receiving a `403 Forbidden`

**Version and platform :**
 - Platform : Linux 
 - Arch : amd64
 - Version : v4.13.0
