### ISSUE TITLE
Docs for Key rewrite show invalid example with bucket prefix

### ISSUE THREAD

**Issue by JuroOravec** [oxyno-zeta/s3-proxy#441]
**Description**

The docs for [key rewrite](https://oxyno-zeta.github.io/s3-proxy/feature-guide/key-rewrite/#s3-prefix) suggest the following:

Given this config:
```yaml
targets:
  - name: test
    # ...
    keyRewriteList:
      - source: ^/file.html$
        target: /redirected/file.html
    bucket:
      # ...
      prefix: "/folder1"
```

Then GET `/file.html` should be rewritten to GET `/folder1/redirected/file.html`.

**HOWEVER**, it seems that currently, the source regex MUST account also for the prefix.

So, to redirect from `/file.html` to `/folder1/redirected/file.html`, given a bucket prefix `/folder1`, we need to do:
```yaml
targets:
  - name: test
    # ...
    keyRewriteList:
      - source: ^/folder1/file.html$
        target: /folder1/redirected/file.html
    bucket:
      # ...
      prefix: "/folder1"
```

The reason for this is because in the code, currently the logic to get the full path including the prefix is called BEFORE the regex matching logic. See https://github.com/oxyno-zeta/s3-proxy/blob/8f1e39b3589171bfd94e1d25cd85c4b8c19e5374/pkg/s3-proxy/bucket/bucket-req-impl.go#L131

**Describe the solution you'd like**

Update the docs to include the correct examples.
