### ISSUE TITLE
Filter listing based on permissions

### ISSUE THREAD

**Issue by dchimeno** [oxyno-zeta/s3-proxy#587]
**Is your feature request related to a problem? Please describe.**

I'm trying to list files with permissions based on oidc groups, it's almost working but I miss an option to only list "folders" or "prefixes" only to those groups.

This is m config.yaml

````yaml

# Log configuration
log:
  level: info
  format: json

# Server configuration
server:
  listenAddr: ""
  port: 8080

# Authentication configuration
authProviders:
  oidc:
    keycloak:
      issuerUrl: http://keycloak:8080/realms/s3-proxy
      clientID: s3-proxy-client
      clientSecret: 
        value: your-client-secret-here
      redirectUrl: http://localhost:8090/auth/oidc/callback
      scopes:
        - openid
        - profile
        - groups
      groupClaim: groups
      loginUrl: /auth/oidc/login
      callbackUrl: /auth/oidc/callback
      cookieName: oidc


# Targets configuration
targets:

  interface:
    mount:
      path:
        - /
    actions:
      GET:
        enabled: true
        config:
          indexDocument: index.html
    bucket:
      name: mybucket.dev.eu
      region: eu-west-1
      prefix: "dashboard/"
      s3Endpoint: ""
      credentials:
        accessKey:
          env: AWS_ACCESS_KEY_ID
        secretKey:
          env: AWS_SECRET_ACCESS_KEY
  
    resources:
      - path: "/*"
        methods:
          - GET
          - HEAD
        provider: keycloak
        oidc:
          authorizationAccesses: []

  files:
    mount:
      path:
        - /files/
    bucket:
      name: mybucket.dev.eu
      region: eu-west-1
      prefix: "files/"
      s3Endpoint: ""
      credentials:
        accessKey:
          env: AWS_ACCESS_KEY_ID
        secretKey:
          env: AWS_SECRET_ACCESS_KEY

    actions:
      GET:
        enabled: true
      HEAD:
        enabled: true
    # Resources with path-based permissions
    resources:
      # Path 120 - only accessible to users with group 120_browser
      - path: "/files/120/*"
        methods:
          - GET
          - HEAD
        provider: keycloak
        oidc:
          authorizationAccesses:
            - group: "120_browser"
        
      # Path 35 - only accessible to users with group 35_browser  
      - path: "/files/35/*"
        methods:
          - GET
          - HEAD
        provider: keycloak
        oidc:
          authorizationAccesses:
            - group: "35_browser"
      
      - path: "/files/*"
        methods:
          - GET
          - HEAD
        provider: keycloak
        oidc:
          authorizationAccesses: []
```

and with dashboard interface applied:

<img width="1133" alt="Image" src="https://github.com/user-attachments/assets/a0f7fd16-f76e-4406-beff-269b7bf45443" />


when logged when user with group 35_browser, I'm still see the listing of 120 although  i can't enter the directory, which is Ok.
