### ISSUE TITLE
Document multi-bucket configuration

### ISSUE THREAD

**Issue by Jan2023-bit** [oxyno-zeta/s3-proxy#593]
The feature list mentions multi-bucket support. But configuration of multiple buckets is not documented and it's unclear to me how to do it.

Maybe the configuration [example](https://oxyno-zeta.github.io/s3-proxy/configuration/example/) in the documentation could be extended in this regard to make usage/adoption of the tool easier?

**Comment by oxyno-zeta** [comment]
Hello @Jan2023-bit ,

In order to use multi-bucket support, you can create a configuration with multiple target following this documentation: https://oxyno-zeta.github.io/s3-proxy/configuration/structure/#targetconfiguration

Here is an example of configuration for 2 buckets:
```yaml
# Targets map
targets:
  first-bucket:
    ## Mount point
    mount:
      path:
        - /first/
    # 
    ## OTHER CONFIGURATION HERE
    # 
    ## Bucket configuration
    bucket:
      name: super-bucket-1
      region: eu-west-1
      disableSSL: false
  second-bucket:
    ## Mount point
    mount:
      path:
        - /second/
    # 
    ## OTHER CONFIGURATION HERE
    # 
    ## Bucket configuration
    bucket:
      name: super-bucket-2
      region: eu-west-1
      disableSSL: false
```

Do not hesitate if you need more details !
